### ISSUE TITLE
*我来了*

### ISSUE THREAD

**Issue by Shirakami-Sora** [Coceki/peko-button#1]
这些按钮怎么用啊peko?

**Comment by Coceki** [comment]
/public/voices文件夹里面是音源，可以换成自己的音源，然后按照我的格式修改/src/assets/voices.json映射文件就可以变成其他的按钮，/src/plugins/vuetify.js文件里面修改primary与secondary的值就可以修改网页的颜色，代码需要使用vue-cli进行编译
