### ISSUE TITLE
建议加上BGM

### ISSUE THREAD

**Issue by cololi** [Coceki/peko-button#2]
[BGM](youtube.com/watch?v=DQweLHdlVWo)

**Comment by cololi** [comment]
网站如果较慢可以把域名挂上CloudFlare

**Comment by Coceki** [comment]
已挂CloudFlare，BGM下次素材大更新可能会加

**Comment by cololi** [comment]
网页的声音有点小（不适合当做循环洗脑BGM

**Comment by Coceki** [comment]
等有空了加一个音量调节
